kramdown:
  parse_block_html: true

permalink: pretty

url: "https://asilata.github.io/"
  
exclude: ['deploy', 'stylesheet.scss']

analytics_id: "UA-52510464-1"

defaults:
  -
    scope:
      path: ""
    values:
      analytics: true

  - scope:
      path: ""
    values:
      robots: true

compress_html:
  clippings: all
  blanklines: true

